export const EVENT_HINTS = [
  // Work & productivity (suffering, but make it charming)
  "Mandatory Fun Meeting",
  "Another Meeting That Could've Been an Email",
  "Pretend to Work Session",
  "Aggressive Scrolling Through Emails",
  "Reply All Aftermath Support Group",
  "Deadline That Snuck Up Like a Ninja",
  "Synergy Alignment Touch-Base",
  "Stand-Up (Please, Sit Down, I'm Begging You)",
  "Quarterly Review of My Life Choices",
  "Inbox Zero Attempt #47",
  "Fighting the Printer",
  "Existential Crisis (Blocked: Waiting on IT)",
  "Performance Review Rehearsal in the Mirror",
  "PowerPoint That Should've Been a Bullet List",
  "Please Read This Slack Message",

  // Food & eating
  "Ritual Cheese Consumption",
  "Convincing Myself Cereal Is a Meal",
  "Emergency Snack Deployment",
  "Leftovers Roulette",
  "Sad Desk Salad",
  "Third Coffee of the Day (No Regrets)",
  "Ordering Pizza and Pretending It's for Everyone",
  "Midnight Fridge Investigation",
  "Brunch With the Chaotic Ones",
  "Soup That Requires Full Commitment",
  "Attempt a Recipe From That Cookbook Gathering Dust",
  "Tapas (an Excuse to Order Everything)",
  "The Great Avocado Toast Experiment",
  "Dinner That Got Ambitious",

  // Social & relationships
  "Chaos Brunch With the Usual Suspects",
  "Pretending to Listen at Family Dinner",
  "Cancelling Plans (in My Heart)",
  "Reluctant Socializing",
  "Wholesome Hangout With No Agenda",
  "Wine and Unfiltered Opinions",
  "Gossip Session (Educational Purposes Only)",
  "Being the Designated Responsible Adult",
  "Talking About Starting a Podcast",
  "Group Chat in Person",
  "Reminiscing About Things That Happened Three Years Ago",
  "Long Walk, Deep Conversation, Bad Decisions",
  "Accidentally Staying Until 2am",
  "Speed-Cleaning Before Guests Arrive",
  "Hosting Anxiety Simulation",

  // Fitness & wellness (the noble struggle)
  "Gym Visit (Mostly Cardio Theater)",
  "Yoga (Napping With Stretching)",
  "Running From My Problems (Literally)",
  "Lift Weights, Feel Less Like a Noodle",
  "Wellness Walk That Became a Snack Run",
  "Aggressive Cycling to Feel Alive",
  "Swimming (Fighting Water)",
  "Stretching While Watching TV — Counts?",
  "Zumba With Absolutely No Shame",
  "Core Workout (Abs Still TBD)",
  "Rest Day (Finally)",
  "Training Montage Energy, Zero Plan",
  "Touch Grass (Doctor's Orders)",
  "Beginner's Mind, Expert's Complaints",
  "Convinced Myself to Enjoy This",

  // Sleep & rest
  "Nap That Gets Out of Hand",
  "Laying in Bed Doing Nothing (Intentional)",
  "Horizontal Thinking Session",
  "12-Hour Sleep Recovery Arc",
  "Reading Until I Pass Out",
  "Darkness and Silence Appreciation Hour",
  "Power Nap (Power Is Aspirational)",
  "Falling Asleep to a Documentary About Cheese",
  "Staring at the Ceiling (Productive Thoughts)",
  "Do Not Disturb: Recharging",

  // Errands & adulting
  "IKEA Expedition (Pack a Lunch)",
  "Tax Situation (It's Fine, It's Fine)",
  "Grocery Shopping With a Loose Plan",
  "Taking That Thing to the Post Office",
  "The Mysterious DMV Visit",
  "Bank Errand From 1987",
  "Dentist (We Don't Talk About It)",
  "Doctor's Appointment: Annual 'So How Are You Really'",
  "Oil Change and Existential Reflection",
  "Finally Calling the Insurance People",
  "Returning the Thing I Should've Returned Months Ago",
  "Appointment I've Been Dreading Since January",
  "Dealing With the Pile",
  "Cleaning That Got Out of Hand",
  "Spending 45 Minutes Finding Parking",

  // Creative & hobbies
  "Painting Something Deeply Abstract",
  "Learning Guitar (Week One, Again)",
  "Writing the Novel (Outlining the Outline)",
  "Photography Walk — Mood: Broody Artiste",
  "Crafting With Chaotic Energy",
  "Starting a Project I Won't Finish",
  "Watching Tutorial Videos Instead of Doing the Thing",
  "Improv Class Where I Embarrass Myself Earnestly",
  "Attempting Pottery (Clay Wins)",
  "Baking Bread Like It's the Apocalypse",
  "Drawing Session: Results May Vary",
  "Music Making With Low Expectations",
  "That Embroidery Project From Two Years Ago",
  "Reading a Book That Has Been on My Shelf for 4 Years",
  "Journaling (Venting but Make It Artsy)",

  // Outdoors & travel
  "Hike That Seemed Shorter on the Map",
  "Park Visit: Doing Absolutely Nothing",
  "Staring at the Ocean Until I Feel Better",
  "Camping (the Luxury Version)",
  "Getting Lost on Purpose",
  "Bird Watching (I'm Becoming My Parent)",
  "Scenic Drive With No Destination",
  "Finding the Best Bench in the City",
  "Picnic With Delusions of Grandeur",
  "Wandering Until Something Looks Interesting",
  "Nature Walk That Became a Mud Situation",
  "Weekend Trip That Will Become a Core Memory",
  "Standing at the Top of Something Tall and Feeling Small",
  "The Beach (Acceptance of Sand in Everything)",
  "Bike Ride, Possibly Legendary",

  // Entertainment & pop culture
  "Movie Marathon (No Shame, All Snacks)",
  "Binge-Watching in Good Conscience",
  "Rewatching That Show for the Third Time",
  "Documentary Deep Dive Into Something Niche",
  "Video Game Session (Just One More Round)",
  "Board Game Night With People Who Take It Too Seriously",
  "Karaoke Night: Courageous Acts",
  "Comedy Show Where I Laugh Too Loud",
  "Concert Front Row (We're Not Okay)",
  "Pub Quiz — Team Name TBD, Spirit Unbreakable",
  "Escape Room: We WILL Get Out This Time",
  "Stand-Up (Sitting Down, Watching Stand-Up)",
  "Cinema Solo — Total Peace",
  "Bookshop Visit With a Budget I Will Ignore",
  "Vintage Market: Hunting for Treasure",

  // Celebrations & milestones
  "Birthday Party for Someone Who Hates Birthdays",
  "Surprise Party Logistics (Terrifying)",
  "Celebrating Something Small That Deserves to Be Big",
  "Toast to Surviving the Week",
  "Making It Through This Month Ceremony",
  "Unironic Dance Party",
  "Anniversary of The Thing That Worked Out",
  "We Didn't Give Up Celebration",
  "Graduation From Bad Habits",
  "Soft Launch of the New Era",

  // Weird, chaotic & deeply relatable
  "Consulting the Stars About a Minor Life Choice",
  "Putting on Actual Pants Day",
  "Revenge Cleaning",
  "Arguing With an Inanimate Object",
  "Dramatically Staring Out of Windows",
  "Eating an Entire Baguette",
  "Sending a Text I've Been Composing for Weeks",
  "Watching Clouds Do Their Thing",
  "Feeding Ducks (A Spiritual Experience)",
  "Rearranging Furniture at 11pm",
  "Convincing Others of My Niche Opinions",
  "Buying Something I Don't Need but Really Want",
  "Grand Re-Opening of My Motivation",
  "Making a List of Lists",
  "Doing the Thing I've Been Avoiding Since March",
  "Answering That Email From Two Months Ago",
  "Crying at a Commercial (It Was Touching)",
  "Talking to My Plants (They Listen Better Than People)",
  "Finding Out What That Noise Was",
  "Spider Relocation Program",
  "Being Unreasonably Excited About a Small Thing",
  "Scheduled Whimsy",
  "Contemplating Whether to Rearrange the Spice Rack",
  "Reading Every Sign in a Museum",
  "Pretending the Coffee Shop Is My Office",
  "That Meeting Where Everyone Agrees We Need Another Meeting",
  "Doing Nothing With Great Intention",
  "Chaotic Good Errands",
  "Reorganizing a Drawer That Was Fine",
  "Becoming Someone Who Wakes Up Early (Attempt #12)",
  "Aggressively Hydrating",
  "Buying Plants I'll Name and Forget",
  "Explaining My Taste in Music to Someone Who Didn't Ask",
  "Watching a Sunset Ironically But Then Getting Into It",
  "Starting a Habit Tracker for My Habit Trackers",
  "Definitely Not Procrastinating",
  "Extremely Chill Crisis Management",
  "Manifesting Things While Lying on the Floor",
];
